# Generated by Django 5.1.4 on 2025-08-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razeruser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='razeruser',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserFileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_history', to='shop.razeruser')),
            ],
        ),
    ]
