# Generated by Django 5.1.4 on 2025-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_razeruser_email_alter_razeruser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razeruser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
