# Generated by Django 5.1.4 on 2025-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_razeruser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='razeruser',
            name='secret_key',
            field=models.CharField(default='default_secret', max_length=255),
            preserve_default=False,
        ),
    ]
