# Generated by Django 5.1.4 on 2025-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_razeruser_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razeruser',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
