# Generated by Django 5.1.4 on 2025-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_razeruser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='razeruser',
            name='regionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
