# Generated by Django 5.1.4 on 2025-09-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_razeruser_regionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='razeruser',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
